version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/battinsight
      - SECRET_KEY=${SECRET_KEY:-devkey123}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your-openai-api-key}
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy  # Wait for postgres to be healthy before starting
    volumes:
      - ../backend:/app/backend
      - ../data:/app/data

  postgres:  # Previously named 'db'
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: battinsight
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: